name: Run Unit Tests

on: [push, pull_request]

jobs:
  test:
    name: Run Jest Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npx jest --coverage

      - name: Debug - List generated files
        run: ls -R

      - name: Ensure Coverage Directory Exists
        run: |
          if [ ! -d "coverage" ]; then
            echo "Coverage directory not found!";
            exit 1;
          fi

      - name: Upload test report (optional)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-report
          path: coverage
